#!/bin/bash

function read_segment() {
  segment=$1
  # generation is at offset=10, size=4
  gen=$(od -j 10 -N 4 -t u4 --endian big -An $segment)
  [ "$gen" -eq "795897447" ] && echo "$segment gen $gen"
  # full generation is at offset=4, size=4, with msb=1 if segment was generated by compaction
  fullGenHex="0x$(od -j 4 -N 4 -t x4 --endian big -An $segment | tr -d '[:space:]')"
  isCompacted=$(( fullGenHex > 31 ))
}

function read_tar() {
  local tarfile=$(realpath $1)
  maxGen=0
  maxCompacted=0

  mkdir tmp-tar && cd tmp-tar
  tar -xf $tarfile
  for segment in $(ls | grep -e ".\{19\}a.\{25\}"); do
    read_segment $segment
    if [ "$gen" -gt "$maxGen" ]; then maxGen=$gen ; fi
    if [ "$isCompacted" -gt "$maxCompacted" ]; then maxCompacted=$isCompacted ; fi
  done

  cd .. && rm -rf tmp-tar
}

for tarfile in $@; do
  read_tar $tarfile
  echo "$(basename $tarfile) $maxGen $maxCompacted"
done

